import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useState } from 'react'
import styles from '../../styles/Home.module.css'
import RestockItem from '../../components/RestockItem'
import TransactionItem from '../../components/TransactionItem'
import Modal from '../../components/Modal'

export default function Detail() {
  const router = useRouter()
  const { id } = router.query
  const [showModal, setShowModal] = useState(false)

  const handleShowModal = () => {
    setShowModal(!showModal)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Detail { id }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {
          showModal ?
          <Modal 
            handleShowModal={handleShowModal}
          /> :
          <></>
        }
        <div className={styles.grid}>
          <RestockItem filled={true} />
          <TransactionItem />
          <TransactionItem />
          <TransactionItem />
          <TransactionItem />
        </div>

        <button className={styles.fab} onClick={handleShowModal}>
          +
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
