import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useState } from 'react'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import RestockItem from '../components/RestockItem'

const Home = () => {
  const apiUrl = process.env.NEXT_PUBLIC_API_URL
  const router = useRouter()
  const [restocks, setRestocks] = useState([])
  const [isLoaded, setIsLoaded] = useState(false)
  const [isLoading, setIsLoading] = useState(false)

  const fetchRestocks = async () => {
    const result = await axios.get(`${apiUrl}/restocks`)
    setRestocks(result.data)
    setIsLoaded(true)
  } 

  const handleDetailRestock = (id) => {
    console.log(id)
    // router.push(`/detail/${id}`)
  }
  
  if(!isLoading) {
    setIsLoading(true)
    fetchRestocks()
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <main className={styles.main}>
        <div className={styles.grid}>
          { 
            isLoaded ?
              restocks.map((restock) => (
                <RestockItem 
                  key={restock.id}
                  restock={restock}
                  onClick={handleDetailRestock.bind(this, restock.id)}
                />
              ))
            : <></>
          }
        </div>
      </main>
  
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
